### ISSUE TITLE
ubuntn18.04已经安装好依赖但使用pip安装仍出现问题

### ISSUE THREAD

**Issue by Whiood** [HuberTRoy/MusicBox#15]
如题：
通过pip安装时提示
Collecting Music-Player
  Downloading https://files.pythonhosted.org/packages/b1/76/7f60397a22625fccf6f80f2da365edac6585ec3d14c14c7edcedc45717a6/Music-Player-1.0.1.tar.gz (171kB)
    100% |████████████████████████████████| 174kB 760kB/s 
Collecting PyQt5 (from Music-Player)
  Could not find a version that satisfies the requirement PyQt5 (from Music-Player) (from versions: )
No matching distribution found for PyQt5 (from Music-Player)

**Comment by HuberTRoy** [comment]
看样子是没有找到合适的PyQt5包，如果你确定已经安装好依赖，可以不必使用pip安装，直接运行music.py即可或者将setup.py里的依赖去掉然后使用`python(3) setup.py install`安装。

可否提供下Python版本，以及具体的系统信息，比如具体的系统位数，PyQt5并不提供32位Linux支持。

**Comment by Whiood** [comment]
系统是64位的Python为3.0
直接运行music.py提示：
hiood@whiood-CP17S:~/下载/Music-Player-1.0.1/MusicPlayer$ ./music.py 
./music.py: 行 8: 
重新设计，主要用于熟悉设计模式。
多线程/漂亮界面的设计等。

以网易云音乐为模板。
# 基本没考虑网络的出错问题。
# 
: 没有那个文件或目录
./music.py: 行 9: $'\r': 未找到命令
./music.py: 行 10: __author__: 未找到命令
./music.py: 行 11: $'\r': 未找到命令
./music.py: 行 15: $'\r': 未找到命令
./music.py: 行 16: 未预期的符号 `(' 附近有语法错误
'/music.py: 行 16: `myFolder = os.path.split(os.path.realpath(__file__))[0]

**Comment by Whiood** [comment]
系统是64位的Python为3.0
直接运行music.py提示：
hiood@whiood-CP17S:~/下载/Music-Player-1.0.1/MusicPlayer$ ./music.py
./music.py: 行 8:
重新设计，主要用于熟悉设计模式。
多线程/漂亮界面的设计等。

以网易云音乐为模板。

基本没考虑网络的出错问题。
: 没有那个文件或目录
./music.py: 行 9: $'\r': 未找到命令
./music.py: 行 10: author: 未找到命令
./music.py: 行 11: $'\r': 未找到命令
./music.py: 行 15: $'\r': 未找到命令
./music.py: 行 16: 未预期的符号 (' 附近有语法错误 '/music.py: 行 16:myFolder =
os.path.split(os.path.realpath(file))[0]

在 2018年5月10日 下午9:22，Cyrbuzz <notifications@github.com>写道：

**Comment by HuberTRoy** [comment]
@Whiood 
运行的话需要
`(sudo) python(3) music.py`

好奇为什么选择3.0这个版本。目前最低支持3.5版本。
