### ISSUE TITLE
为什么一定要 sudo 权限？

### ISSUE THREAD

**Issue by xhao79** [HuberTRoy/MusicBox#17]
如题
如何在不需要 sudo 权限的情况下运行 musicplayer ?

**Comment by HuberTRoy** [comment]
@xhao79 
默认情况下图片是缓存在安装目录的，所以如果想不带sudo可以更改图片缓存目录到一个拥有写和读权限的目录下。
缓存目录可以在`base.py`中更改`cacheFolder`实现。
或者也可以将musicplayer安装在一个拥有可读可写权限的目录下。

加入TODO:
`变更默认缓存目录到用户文件夹下`。
