### ISSUE TITLE
尝试重新获取音乐地址出错

### ISSUE THREAD

**Issue by chuangzhanji** [HuberTRoy/MusicBox#18]
**请简要描述下这个Bug**
 logger.error("尝试重新获取音乐地址出错，音乐信息: {0}".format(musicInfo), exc_info=True)
UnboundLocalError: local variable 'musicInfo' referenced before assignment

**请描述下重现步骤**
首次启动，搜索无反应，打开其中一个歌单播放全部，然后闪退。

**系统信息**
Windows 10
Python3.6.4 :: Anaconda custom (64-bit)
校园网

**Comment by HuberTRoy** [comment]
感谢告知~，已尝试进行修复。
原因应该是校园网不允许访问网易云的服务器，请尝试使用代理。
