### ISSUE TITLE
win10已经安装成功了，但是怎么运行呢？

### ISSUE THREAD

**Issue by Mikchy** [HuberTRoy/MusicBox#19]

**Comment by Mikchy** [comment]
Finished processing dependencies for Music-Player==1.0.5.1
显示出来这个了，应该是python3 setup.py install成功了
那现在怎么运行出来呢？

**Comment by HuberTRoy** [comment]
@Mikchy 
打开命令行，输入`musicplayer`，用力敲一下回车。注意，这里一定要用力，否则可能会出现异常！
然后等待打开或者报了一个错。
如果是第二种情况，请提交bug！

玩的开心~：）

**Comment by Mikchy** [comment]
![image](https://user-images.githubusercontent.com/39512798/40363959-99bf10c8-5e03-11e8-8963-44fd1c9a53ec.png)
@HuberTRoy

**Comment by Mikchy** [comment]
这个是啥子情况呢？谢谢
@HuberTRoy

**Comment by HuberTRoy** [comment]
如果你确定已经安装成功，请检查是否将 `Python目录/Scripts`添加到了环境路径中。
如果已经添加到环境路径中仍不能启动，可以直接运行源码中的`music.py`进行启动。
