### ISSUE TITLE
QQ音乐的解码器具体如何安装

### ISSUE THREAD

**Issue by Pcject** [HuberTRoy/MusicBox#20]
直接下载安装后没用
控制台报错如下：
DirectShowPlayerService::doSetUrlSource: Unresolved error code 0x800c0008 (??????????????)
另外，我目前在做的音乐推荐是用QQ音乐的最新的两百万歌单（爬虫爬下来的）与其中所包含的四百万左右的歌曲进行分析推荐，然后能获取到QQ音乐的原始主键（songid和songmid），能告诉我下怎么播放音乐吗？

**Comment by Pcject** [comment]
暂时采取的方案是使用Selenium去模拟真实用户打开音乐播放页面，然后将浏览器内核隐藏，将用户操作映射到网页的点击事件，但这样占内存较大，本身整个模型的占用内存也非常大了

**Comment by HuberTRoy** [comment]
看样子QQ音乐更改了获取歌曲URL的方法，导致旧的获取方法失效，待修复....

要播放音乐首先要获取到它的播放地址，也就是上面说的暂时失效的方法。

**Comment by Pcject** [comment]
好的，谢谢，我时间不够了，就用Selenium操控chromedriver包了一层壳子作为客户端先用了

**Comment by HuberTRoy** [comment]
@Pcject 
已更新QQ音乐源，详情请看`apis/qqApi.py`文件。

获取出音乐地址后可使用任意可以解码的播放器播放。
