### ISSUE TITLE
What is the login details for the app?

### ISSUE THREAD

**Issue by Isuru29** [HuberTRoy/MusicBox#23]
**请简要描述下这个Bug**

**请描述下重现步骤**
如:
1. 在 '...' 页面。
2. 点了 '....' 按钮。
3. 稍微滚了一下 '....'。
4. 就看到了Bug。

**如果不发生Bug本该如何**

**相关截图，日志**
如果有相关截图，请提供~。
请务必把目录下的日志提供一份~。

**系统信息**
 - OS: [e.g. Windows]

**其他**

**Comment by HuberTRoy** [comment]
You can login in by your registered phone number on netease.
MusicBox will show the playlist that you favorite and created.
