### ISSUE TITLE
无法播放 playlist

### ISSUE THREAD

**Issue by WangNianyi2001** [HuberTRoy/MusicBox#25]
安装完成并 sudo 运行之后可以读取本地音乐列表，双击也能添加至 playlist 中，但就是无法播放

**相关截图，日志**
![screenshot from 2018-09-26 21-15-48](https://user-images.githubusercontent.com/19430435/46082296-5dc02800-c1d1-11e8-9d23-9d6835ba4aba.png)

**系统信息**
Ubuntu 18.04.1 LTS
7.5 GB RAM
Intel Core i5-4210U CPU @ 1.70GHz x 4
Gnome 3.28.2
64-bit

**Comment by HuberTRoy** [comment]
@WangNianyi2001 
尝试安装下播放依赖和解码器：
```
$ sudo apt-get install pyqt5.qtmultimedia
$ sudo apt-get install libqt5multimedia5-plugins
```
解码器：
[Gstreamer](https://gstreamer.freedesktop.org/)
非 `m4a` 格式可以不安装 Gstreamer.

**Comment by WangNianyi2001** [comment]
还是不行啊（
terminal 显示什么“音乐地址错误，请删除错误路径”啥的

**Comment by HuberTRoy** [comment]
@WangNianyi2001 
如果网络歌曲可播放，请右键音乐列表然后清空并重新添加一下歌曲播放，如果还不行，请反馈一下，这应该是个BUG。
如果不可播放，应该是其他原因，请检查下解码器有无正确安装，相关依赖是否已经具备。

**Comment by WangNianyi2001** [comment]
网络歌曲也不行……
gstreamer 我这里看是安装完了的
最好直接报个 bug 吧orz
