### ISSUE TITLE
No module named 'PyQt5.QtMultimedia'

### ISSUE THREAD

**Issue by Ssunhx** [HuberTRoy/MusicBox#26]
你好：
       我安装所有的依赖包后，都没有问题，但是在使用MusicPlayer启动程序时，会曝出错误：
       
<img width="715" alt="error" src="https://user-images.githubusercontent.com/39128611/47289260-69660980-d62c-11e8-9fde-b0297c367ce7.PNG">
 我检查了pyqt5，没有发现问题，不知道是哪出现问题了？？
我的环境是win10 64，python3.5.3

**Comment by HuberTRoy** [comment]
看样子是 PyQt5 的播放组件没有安装上，如果 `pip` 没有安装上，Windows 的话直接找下对应的 `exe` 安装下吧。
https://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.6/
