### ISSUE TITLE
请问一下 怎么才能获取播放的一些相关信息，比如播放时间

### ISSUE THREAD

**Issue by pugnazhaotianqi** [HuberTRoy/MusicBox#27]
**请简要描述下该功能**

**请描述下要注意的细节**

**请描述下最终实现效果**

**请提供一份想法说明~**
想法成因，如 在听歌时发现比较迷茫，于是想要个推荐系统/看手气听随机歌曲的功能。

**其他补充**
截图，或其他相关资料。

**Comment by HuberTRoy** [comment]
1. 写在API信息里的。如果你想问的是这种情况，请看[文档的API部分](https://github.com/HuberTRoy/MusicBox/blob/master/doc/document.md#neteaseapi) 配合代码食用更佳。 同时如果需要抓包的简略教程分析请看文档的[抓包简析](https://github.com/HuberTRoy/MusicBox/tree/master/doc/analysis)。

2. MP3 或者其他格式的歌曲文件。如果是这种情况可以搜一下歌曲解析的库，如项目中用到的 eyed3 ，并配合其文档说明找到获取信息的办法。

如果以上两种情况都不是请说明。

**Comment by pugnazhaotianqi** [comment]
十分感谢您的回复
我描述一下我想要做的事情吧，目前我想通过播放器做一个简单的实时频域分析，所以想要获得进度条的具体时间、歌曲播放的ur、以及歌曲的播放状态这三个变量。由于我刚学习pyqt所以对pyqt不是太熟悉，所以想请问这些数据您放在哪个模块。
烦请多多指教。

**Comment by HuberTRoy** [comment]
@pugnazhaotianqi 
可以看一下 `widgets/player.py` 里的 [`Player`](https://github.com/HuberTRoy/MusicBox/blob/master/MusicPlayer/widgets/player.py#L925) 类。
同时可以看一下`PyQt5`文档中 [`QMediaPlayer`](http://doc.qt.io/qt-5/qmediaplayer.html#signals) 的相关资料。

根据你的需求的话着重看一下两者的`信号槽`部分。

**Comment by pugnazhaotianqi** [comment]
@HuberTRoy 
谢谢大佬，目前我用源码发现你的上一曲和下一曲按钮对应的功能反过来了
囧

**Comment by HuberTRoy** [comment]
@pugnazhaotianqi 
上一曲下一曲是按照播放列表里的顺序来的，也就是右下角那个小东西点开，好像没有反？

**Comment by pugnazhaotianqi** [comment]
恩恩  是我看错了
