### ISSUE TITLE
支持歌词不? 

### ISSUE THREAD

**Issue by biluohc** [HuberTRoy/MusicBox#3]
给个你star支持下,期待能代替客户端的那天.

**Comment by HuberTRoy** [comment]
@biluohc 
谢谢支持~。

今天刚更新歌词，和原版网易云音乐一样，点击缩略图即可查看详情。目前是获取并显示，进一步还没有完善。简单说明可看下[开发日志](https://github.com/HuberTRoy/MusicPlayer/blob/master/doc/updateLog.md)。

**Comment by biluohc** [comment]
如果能支持音乐云盘就能尝试迁移过去, 网易的版权真是每天灰一片.

**Comment by HuberTRoy** [comment]
@biluohc 

暂时未寻找云盘相关的API。

整合多个音乐平台的资源已加入TODO~。

**Comment by biluohc** [comment]
好吧,
果然维护这种东西最好自己有分析api的能力.

**Comment by HuberTRoy** [comment]
@biluohc 

有兴趣可以一起来做~。

**Comment by biluohc** [comment]
没写过pyqt5, py 本身都不太熟悉哈

**Comment by HuberTRoy** [comment]
@biluohc 
好吧，再次感谢支持~。
