### ISSUE TITLE
我是在mac下  运行后产生的cookies文件下和其子文件夹mediaPlaylist,playlist下的.cks文件一直是空  这是怎么回事呢?... 作者你能提供这几份.cks文件吗? 多谢了.... 急急急

### ISSUE THREAD

**Issue by CoderPeak** [HuberTRoy/MusicBox#32]

**Comment by CoderPeak** [comment]
我是在mac下  运行后产生的cookies文件下和其子文件夹mediaPlaylist,playlist下的.cks文件一直是空  这是怎么回事...  作者能提供.cks文件吗

**Comment by HuberTRoy** [comment]
@CoderPeak 
playlist是播放列表的历史，如果没有播放历史或者清空了的话是不会存在的。

cks文件使用pickle保存的，你可以自己用pickle写一份。
数据类型：
```
[
{'name': str, 'time': str, 'author': str, music_img: None/url},
... 
]
```

**Comment by CoderPeak** [comment]
已经解决了, 多谢......   不过  我自己之前测试自己的pyqt5项目的时候  打app包, 图片资源啥的老是打包不进去。  打的包没有图片资源, 这个是要怎么解决的啊...   图片要怎么打到包里去

**Comment by HuberTRoy** [comment]
@CoderPeak 
图片都用的相对目录，所以可以打包完成后直接把图片复制过去，比如：
```
icon/
   icon.png
music.py
```
打包如果只有
```
music.app (不知道mac的应用后缀是什么...)
```
可以手抖把icon目录拖进去：
```
music.app
icon/
   icon.png
```
另外如果用pyinstaller打包的话，而且坚持想要单文件，你可以看下[这页文档](https://pythonhosted.org/PyInstaller/runtime-information.html)，这个是讲单文件是如何运行的。
