### ISSUE TITLE
可以加一个requestment.txt 吗？

### ISSUE THREAD

**Issue by zhangslob** [HuberTRoy/MusicBox#4]
按照你的要求，已经安装

> Python
> PyQt
> requests
> eyed3
> crypto/cryptodome
> quamash

运行代码，提示
`failed to find libmagic.  Check your installation`

用的Python3.6，是因为不支持3.6吗？

**Comment by zhangslob** [comment]
以及
`QQ 播放地址获取失败，请勿播放QQ音乐。`

**Comment by zhangslob** [comment]
好像是windows下libmagic文件缺失

**Comment by HuberTRoy** [comment]
@zhangslob 
似乎你已经解决了libmagic的问题。如果没解决可看下:
[python-magic](https://stackoverflow.com/questions/18318076/python-magic-installation-error-importerror-failed-to-find-libmagic)

我还收到一个不能播放QQ音乐的提醒： 
QQ音乐的格式是m4a，需要下载相应的解码器。
Windows下如果缺少可以安装:
<a href="https://github.com/Nevcairiel/LAVFilters/releases">LAV Filters</a>
Linux下需要安装:
<a href="https://gstreamer.freedesktop.org/">GStreamer</a>

刚刚在readme中更新了所需依赖。以及更新了QQ音乐的搜索功能。

**Comment by zhangslob** [comment]
多谢
