### ISSUE TITLE
MV怎么实现播放

### ISSUE THREAD

**Issue by ghost** [HuberTRoy/MusicBox#42]
**请简要描述下该功能**

**请描述下要注意的细节**

**请描述下最终实现效果**

**请提供一份想法说明~**
想法成因，如 在听歌时发现比较迷茫，于是想要个推荐系统/看手气听随机歌曲的功能。

**其他补充**
截图，或其他相关资料。

**Comment by qiyiyu** [comment]
通过MV可以播放音乐的MV

**Comment by HuberTRoy** [comment]
@qiyiyu 
可查看Qt文档索引到相关的API。
