### ISSUE TITLE
能不能把音乐进行分类

### ISSUE THREAD

**Issue by ghost** [HuberTRoy/MusicBox#43]
**请简要描述下该功能**
将音乐分成跑步、睡觉、英语等类型
**请描述下要注意的细节**

**请描述下最终实现效果**

**请提供一份想法说明~**
想法成因，如 在听歌时发现比较迷茫，于是想要个推荐系统/看手气听随机歌曲的功能。

**其他补充**
截图，或其他相关资料。

**Comment by HuberTRoy** [comment]
@qiyiyu 
本项目没有原始歌曲数据库，能不能分类取决于他们本身是否被分类过。
