### ISSUE TITLE
eyed3没有0.8.0这个版本

### ISSUE THREAD

**Issue by 19930618** [HuberTRoy/MusicBox#46]
**请简要描述下这个Bug**
安装提示没有eyed3==0.8.0
**请描述下重现步骤**
如:
1. 在 '...' 页面。
2. 点了 '....' 按钮。
3. 稍微滚了一下 '....'。
4. 就看到了Bug。

**如果不发生Bug本该如何**

**相关截图，日志**
如果有相关截图，请提供~。
请务必把目录下的日志提供一份~。

**系统信息**
 - OS: [e.g. Windows]

**其他**

**Comment by HuberTRoy** [comment]
@19930618 
似乎已经被删掉了，
可下载其他版本做适配~。
