### ISSUE TITLE
cookies是空的，好像，大佬能指导一下吗?界面是能搜索到歌曲中，但是不能播放。

### ISSUE THREAD

**Issue by haojiam** [HuberTRoy/MusicBox#52]
读取或保存cookies出错 ['cookies/playlist/musicList.cks']
读取或保存cookies出错 ['cookies/mediaPlaylist/musics.cks', 'cookies/mediaPlaylist/mediaList.cks']
读取或保存cookies出错 ['cookies/headers/loginInfor.cks']
读取或保存cookies出错 ['cookies/downloadInfo/downloadFolder.cks']
读取或保存cookies出错 ['cookies/native/local.cks']
![}I4G%}O{X}INJD($)76KM0L](https://github.com/HuberTRoy/MusicBox/assets/94657663/d898574c-c2ec-4ce6-8c2a-d4c13af4d376)

**Comment by HuberTRoy** [comment]
Hi, 项目已不再维护。可以关注一下https://github.com/feeluown/FeelUOwn这个更优秀的作品~.

**Comment by haojiam** [comment]
谢谢大佬。
