### ISSUE TITLE
测试好之后再提交呀

### ISSUE THREAD

**Issue by Apuyuseng** [HuberTRoy/MusicBox#7]
折腾了半小时， 新添加的日志有问题， logger 模块找不到
1. 安装时没有安装进去，请再logger夹下添加 __init__.py文件，Python知道他时个模块。
2. 放个音乐还要sudo权限，风险很大。
3. 日志放在临时目录里面，放在dist-packages里面算怎么回事。

**Comment by HuberTRoy** [comment]
非常抱歉，带来了很大的麻烦。
已修复该问题，感谢提交Bug。
关于__init__.py的添加这个是一直以来的问题，最早的时候没有使用相对目录的方式导入模块，现在改起来有些麻烦，不太影响使用暂时没有整改。最近想进行打包貌似也会有些问题(使用相对目录后)，可能是姿势不对。

关于sudo权限，主要是默认的缓存目录在程序同文件夹下，下载图片时会进行写入。用不用sudo取决于缓存目录的设置。目前有两种方法: 1. 修改base.py里的缓存目录。2. 将主程序放在一个有写权限的目录。

日志有这个要求吗？第一次写不太清楚。

再次感谢反馈。：）
