### ISSUE TITLE
如何卸载？

### ISSUE THREAD

**Issue by yujqiao** [HuberTRoy/MusicBox#8]
（还有readme里的安装步骤没cd）

**Comment by HuberTRoy** [comment]
@Rapiz1 
可使用`pip(3) uninstall Music_Player`.
或者找到目录也可直接删除，除了手动设置不会对安装目录以外目录有使用行为。目前的图片(歌曲)缓存/cookies等都是保存在安装目录。

**Comment by lqrqw13** [comment]
运行时会报错，然后搜索用不了
DirectWrite: CreateFontFaceFromHDC() failed (指示输入文件 (例如字体文件) 中的错误。) for QFontDef(Family="System", pointsize=16, pixelsize=16, styleHint=5, weight=9, stretch=100, hintingPreference=0) LOGFONT("System", lfWidth=0, lfHeight=-16) dpi=96
DirectShowPlayerService::doSetUrlSource: Unresolved error code 0x80040216 (IDispatch error #22)
DirectShowPlayerService::doSetUrlSource: Unresolved error code 0x80040216 (IDispatch error #22)
DirectShowPlayerService::doSetUrlSource: Unresolved error code 0x80040216 (IDispatch error #22)

**Comment by HuberTRoy** [comment]
@lqrqw13 
方便按照bug上报格式重新编辑一下吗。
